# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20170426_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trips',
            field=models.ManyToManyField(related_name='trip_users', to='exam_app.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
