# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20170426_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='exam_app.User'),
            preserve_default=False,
        ),
    ]
